# changes to documentation generation
"area/docs-generation": 
- changed-files:
  - any-glob-to-any-file: 'doc/**'

# changes to the core kdebug command
"area/kdebug-command":
- changed-files:
  - any-glob-to-any-file: ['./kdebug.go', './kdebug_test.go', './*command*.go']

# changes made to command flags/args
"area/flags":
- changed-files:
  - any-glob-to-any-file: './args*.go'

# changes to Github workflows
"area/github":
- changed-files:
  - any-glob-to-any-file: '.github/**'

# changes to shell completions
"area/shell-completion":
- changed-files:
  - any-glob-to-any-file: './*completions*'