run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - gosec
    - goconst
    - misspell
    - unconvert
    - unparam
    - nakedret
    - prealloc
    - gocritic
    - asciicheck
    - errorlint

  disable:
    - gochecknoinits
    - gochecknoglobals
    - funlen
    - lll
    - nlreturn
    - testpackage
    - wsl
    - whitespace
    - dogsled
    - bodyclose
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - gofumpt
    - gocyclo

linters-settings:
  govet:
    disable:
      - fieldalignment
      - shadow
  
  gosec:
    excludes:
      - G204
      - G304

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - goconst
        - unparam